apiVersion: v1
kind: Secret
metadata:
  name: wopi-service-secrets
type: Opaque
stringData:
  database-host: "postgres-host"
  database-username: "wopi"
  database-password: "CHANGE_ME"
  nats-url: "nats://nats:4222"
  token-secret: "CHANGE_ME"
